### PR TITLE
Made it give me less depression

### PR DESCRIPTION
**Pull request by ar1ja**

### CODE REVIEW

**Review by ar1ja — COMMENTED** [review]
Yep gives me less depression

**Comment by uday-kalyan-s** [comment]
damn thanks for the ui update. im not very good with md files.

**Comment by uday-kalyan-s** [comment]
Do I know u btw? How did u know I was trying to migrate from angular to svelte? I only considered it recently. And that I gave up on rust.

**Comment by ar1ja** [comment]
> Do I know u btw? How did u know I was trying to migrate from angular to svelte? I only considered it recently. And that I gave up on rust.

Yeah you know me, just that I don't want you to remember you, we met on TCD, but I don't use discord anymore so heh, just sorry if you remember me lol, we have not talked in like a year and I just removed angular because a

**Comment by uday-kalyan-s** [comment]
A?

**Comment by ar1ja** [comment]
> A?

I prefer m

**Pull request merged**
